apiVersion: v1
kind: ConfigMap
metadata:
  name: paymybuddy-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
    {{- include "paymybuddy.labels" . | nindent 4 }}
data:
  MYSQL_DATABASE: {{ .Values.mysql.database.name | quote }}
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:{{ .Values.mysql.service.port }}/{{ .Values.mysql.database.name }}"
  SPRING_DATASOURCE_USERNAME: {{ .Values.mysql.database.user | quote }}
  SPRING_JPA_HIBERNATE_DDL_AUTO: {{ .Values.config.springJpaHibernateDdlAuto | quote }}
